/**
 * ERP-Lite posting constants.
 *
 * These constants mirror the approved runtime contract so the posting engine
 * does not rely on ad hoc string literals for finance-critical behavior.
 */

export const ERP_LITE_AMOUNT_SOURCES = {
  NET_AMOUNT: 'NET_AMOUNT',
  TAX_AMOUNT: 'TAX_AMOUNT',
  GROSS_AMOUNT: 'GROSS_AMOUNT',
  DISCOUNT_AMOUNT: 'DISCOUNT_AMOUNT',
  DELIVERY_FEE_AMOUNT: 'DELIVERY_FEE_AMOUNT',
  ROUNDING_AMOUNT: 'ROUNDING_AMOUNT',
  CUSTOM_EXPR: 'CUSTOM_EXPR',
} as const;

export const ERP_LITE_ENTRY_SIDES = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
  DR: 'DR',
  CR: 'CR',
} as const;

export const ERP_LITE_ATTEMPT_STATUSES = {
  INITIATED: 'INITIATED',
  VALIDATED: 'VALIDATED',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
  FAILED_RULE: 'FAILED_RULE',
  FAILED_ACCOUNT: 'FAILED_ACCOUNT',
  FAILED_SYSTEM: 'FAILED_SYSTEM',
  POSTED: 'POSTED',
  REVERSED: 'REVERSED',
} as const;

export const ERP_LITE_LOG_STATUSES = {
  PREVIEWED: 'PREVIEWED',
  POSTED: 'POSTED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
  REVERSED: 'REVERSED',
} as const;

export const ERP_LITE_EXCEPTION_TYPES = {
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  AMBIGUOUS_RULE: 'AMBIGUOUS_RULE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  PERIOD_CLOSED: 'PERIOD_CLOSED',
  DUPLICATE_POST: 'DUPLICATE_POST',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_NOT_POSTABLE: 'ACCOUNT_NOT_POSTABLE',
  MISSING_USAGE_MAPPING: 'MISSING_USAGE_MAPPING',
  ACCOUNT_TYPE_MISMATCH: 'ACCOUNT_TYPE_MISMATCH',
} as const;

export const ERP_LITE_EXCEPTION_STATUSES = {
  NEW: 'NEW',
} as const;

export const ERP_LITE_POSTING_MODES = {
  PREVIEW: 'preview',
  EXECUTE: 'execute',
  RETRY: 'retry',
  REPOST: 'repost',
} as const;

export const ERP_LITE_TXN_EVENT_CODES = {
  ORDER_INVOICED: 'ORDER_INVOICED',
  ORDER_SETTLED_CASH: 'ORDER_SETTLED_CASH',
  ORDER_SETTLED_CARD: 'ORDER_SETTLED_CARD',
  ORDER_SETTLED_WALLET: 'ORDER_SETTLED_WALLET',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  REFUND_ISSUED: 'REFUND_ISSUED',
  EXPENSE_RECORDED: 'EXPENSE_RECORDED',
  PETTY_CASH_TOPUP: 'PETTY_CASH_TOPUP',
  PETTY_CASH_SPENT: 'PETTY_CASH_SPENT',
} as const;

export const ERP_LITE_BLOCKING_MODES = {
  BLOCKING: 'BLOCKING',
  NON_BLOCKING: 'NON_BLOCKING',
} as const;

export const ERP_LITE_FAILURE_ACTIONS = {
  BLOCK_TXN: 'BLOCK_TXN',
  FINANCE_EXCEPTION: 'FINANCE_EXCEPTION',
} as const;

export const ERP_LITE_PAYMENT_USAGE_MAP = {
  CASH: 'CASH_MAIN',
  CARD: 'BANK_CARD_CLEARING',
  CHECK: 'BANK_CARD_CLEARING',
  BANK_TRANSFER: 'BANK_CARD_CLEARING',
  MOBILE_PAYMENT: 'BANK_CARD_CLEARING',
  HYPERPAY: 'BANK_CARD_CLEARING',
  PAYTABS: 'BANK_CARD_CLEARING',
  STRIPE: 'BANK_CARD_CLEARING',
  WALLET: 'WALLET_CLEARING',
} as const;

export type ErpLiteAmountSource =
  (typeof ERP_LITE_AMOUNT_SOURCES)[keyof typeof ERP_LITE_AMOUNT_SOURCES];
export type ErpLiteAttemptStatus =
  (typeof ERP_LITE_ATTEMPT_STATUSES)[keyof typeof ERP_LITE_ATTEMPT_STATUSES];
export type ErpLiteLogStatus =
  (typeof ERP_LITE_LOG_STATUSES)[keyof typeof ERP_LITE_LOG_STATUSES];
export type ErpLiteExceptionType =
  (typeof ERP_LITE_EXCEPTION_TYPES)[keyof typeof ERP_LITE_EXCEPTION_TYPES];
export type ErpLitePostingMode =
  (typeof ERP_LITE_POSTING_MODES)[keyof typeof ERP_LITE_POSTING_MODES];
export type ErpLiteTxnEventCode =
  (typeof ERP_LITE_TXN_EVENT_CODES)[keyof typeof ERP_LITE_TXN_EVENT_CODES];
export type ErpLiteBlockingMode =
  (typeof ERP_LITE_BLOCKING_MODES)[keyof typeof ERP_LITE_BLOCKING_MODES];
