/**
 * Feature flags — single source of truth
 * Source: hq_ff_feature_flags_mst (Supabase remote)
 * Regenerate: Supabase MCP execute_sql → scripts/extract-flag-catalog.js → scripts/generate-flag-catalog.js
 * Sync with database when adding or changing flags.
 */

import type { FeatureFlags } from '@/lib/types/tenant';

// ========================
// Catalog Types
// ========================

export type PlanBindingType = 'plan_bound' | 'independent';
export type FlagDataType = 'boolean' | 'integer' | 'string' | 'object';

export type GovernanceCategory = 'tenant_feature' | 'tenant_limit' | 'hq_feature' | 'hq_config' | 'experimental' | 'beta';

export interface FlagCatalogEntry {
  flag_key: string;
  flag_name: string;
  plan_binding_type: PlanBindingType;
  data_type: FlagDataType;
  default_value: boolean | number | string | Record<string, unknown>;
  /** UI grouping (from hq_ff_feature_flags_mst.ui_group) */
  ui_group?: string;
  /** Governance category (tenant_feature, tenant_limit, hq_feature, etc.) */
  governance_category?: GovernanceCategory;
  /** Display order within ui_group */
  ui_display_order?: number;
}

export type TenantSettingDefaultValue = boolean | number | string | Record<string, unknown>;
export type FeatureFlagKey = keyof FeatureFlags;

// ========================
// Catalog (single source)
// ========================

export const FLAG_CATALOG: FlagCatalogEntry[] = [
  { flag_key: 'ai_damage_detection', flag_name: 'AI Damage Detection', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'barcode_scanning', flag_name: 'Barcode Scanning', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'image_recognition', flag_name: 'Image Recognition', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_language', flag_name: 'Multi-Language Support', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'qr_code_generation', flag_name: 'QR Code Generation', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'rtl_support', flag_name: 'RTL Support', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Advanced', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'advanced_analytics', flag_name: 'Advanced Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'custom_reports', flag_name: 'Custom Reports', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_analytics', flag_name: 'Customer Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'export_reports', flag_name: 'Export Reports', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_analytics', flag_name: 'Order Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'performance_dashboard', flag_name: 'Performance Dashboard', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'revenue_analytics', flag_name: 'Revenue Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'tenant_advanced_analytics', flag_name: 'Advanced Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 20 },
  { flag_key: 'tenant_api_access', flag_name: 'API Access', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Analytics', governance_category: 'tenant_feature', ui_display_order: 21 },
  { flag_key: 'tenant_new_dashboard_ui', flag_name: 'New Dashboard UI', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'Beta Features', governance_category: 'beta', ui_display_order: 50 },
  { flag_key: 'tenant_pdf_invoices', flag_name: 'PDF Invoices', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Billing Features', governance_category: 'tenant_feature', ui_display_order: 1 },
  { flag_key: 'tenant_whatsapp_receipts', flag_name: 'WhatsApp Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Billing Features', governance_category: 'tenant_feature', ui_display_order: 2 },
  { flag_key: 'tenant_in_app_receipts', flag_name: 'In-App Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Billing Features', governance_category: 'tenant_feature', ui_display_order: 3 },
  { flag_key: 'tenant_custom_domain', flag_name: 'Custom Domain', plan_binding_type: 'plan_bound', data_type: 'string', default_value: '', ui_group: 'Branding', governance_category: 'tenant_feature', ui_display_order: 60 },
  { flag_key: 'tenant_branding_config', flag_name: 'Branding Configuration', plan_binding_type: 'plan_bound', data_type: 'object', default_value: {}, ui_group: 'Branding', governance_category: 'tenant_feature', ui_display_order: 61 },
  { flag_key: 'bulk_pricing', flag_name: 'Bulk Pricing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Catalog', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'pricing_rules', flag_name: 'Pricing Rules', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Catalog', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'product_variants', flag_name: 'Product Variants', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Catalog', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'service_catalog', flag_name: 'Service Catalog', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Catalog', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'service_categories', flag_name: 'Service Categories', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Catalog', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'email_receipts', flag_name: 'Email Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_reminders', flag_name: 'Order Reminders', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'push_notifications', flag_name: 'Push Notifications', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sms_notifications', flag_name: 'SMS Notifications', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'whatsapp_notifications', flag_name: 'WhatsApp Notifications', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'whatsapp_receipts', flag_name: 'WhatsApp Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Communication', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'address_management', flag_name: 'Address Management', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_history', flag_name: 'Order History', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_notes', flag_name: 'Customer Notes', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_profiles', flag_name: 'Customer Profiles', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_segments', flag_name: 'Customer Segmentation', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_tags', flag_name: 'Customer Tags', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Customer Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'delivery_optimization', flag_name: 'Delivery Optimization', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Delivery', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'delivery_scheduling', flag_name: 'Delivery Scheduling', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Delivery', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'delivery_tracking', flag_name: 'Delivery Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Delivery', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'delivery_zones', flag_name: 'Delivery Zones', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Delivery', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'driver_assignment', flag_name: 'Driver Assignment', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Delivery', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'tenant_beta_ai_classification', flag_name: 'AI Order Classification (Beta)', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'Experimental', governance_category: 'experimental', ui_display_order: 40 },
  { flag_key: 'tenant_beta_voice_orders', flag_name: 'Voice Order Entry (Beta)', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'Experimental', governance_category: 'experimental', ui_display_order: 41 },
  { flag_key: 'accounting_export_enabled', flag_name: 'Accounting Export Enabled', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'erp_lite_enabled', flag_name: 'ERP-Lite Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 1 },
  { flag_key: 'erp_lite_gl_enabled', flag_name: 'ERP-Lite GL', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 2 },
  { flag_key: 'erp_lite_reports_enabled', flag_name: 'ERP-Lite Financial Reports', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 3 },
  { flag_key: 'erp_lite_ar_enabled', flag_name: 'ERP-Lite AR Aging', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 4 },
  { flag_key: 'erp_lite_expenses_enabled', flag_name: 'ERP-Lite Expenses', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 5 },
  { flag_key: 'erp_lite_bank_recon_enabled', flag_name: 'ERP-Lite Bank Reconciliation', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 6 },
  { flag_key: 'erp_lite_ap_enabled', flag_name: 'ERP-Lite Accounts Payable', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 7 },
  { flag_key: 'erp_lite_po_enabled', flag_name: 'ERP-Lite Purchase Orders', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 8 },
  { flag_key: 'erp_lite_branch_pl_enabled', flag_name: 'ERP-Lite Branch P&L', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 9 },
  { flag_key: 'erp_lite_readiness_enabled', flag_name: 'ERP-Lite Finance Readiness', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 10 },
  { flag_key: 'erp_lite_usage_map_enabled', flag_name: 'ERP-Lite Usage Mapping', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 11 },
  { flag_key: 'erp_lite_exceptions_enabled', flag_name: 'ERP-Lite Exception Workbench', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 12 },
  { flag_key: 'erp_lite_periods_enabled', flag_name: 'ERP-Lite Period Management', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 13 },
  { flag_key: 'erp_lite_post_audit_enabled', flag_name: 'ERP-Lite Posting Audit', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'ERP-Lite', governance_category: 'tenant_feature', ui_display_order: 14 },
  { flag_key: 'advance_payments_enabled', flag_name: 'Advance Payments Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'advanced_analytics_enabled', flag_name: 'Advanced Analytics Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'advanced_roles_enabled', flag_name: 'Advanced Roles Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_churn_prediction', flag_name: 'Ai Churn Prediction', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_features_explainable_only', flag_name: 'Ai Features Explainable Only', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_feedback_capture', flag_name: 'Ai Feedback Capture', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_pricing_estimator', flag_name: 'Ai Pricing Estimator', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_ready_by_prediction', flag_name: 'Ai Ready By Prediction', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_recommendations_enabled', flag_name: 'Ai Recommendations Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_routing_eta', flag_name: 'Ai Routing Eta', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ai_vision_qa', flag_name: 'Ai Vision Qa', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'api_access_enabled', flag_name: 'Api Access Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'approval_required_for_refunds', flag_name: 'Approval Required For Refunds', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'assembly_bin_location_tracking', flag_name: 'Assembly Bin Location Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'assembly_capacity_limits', flag_name: 'Assembly Capacity Limits', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_limit', ui_display_order: 0 },
  { flag_key: 'assembly_completeness_check', flag_name: 'Assembly Completeness Check', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'assembly_stage_enabled', flag_name: 'Assembly Stage Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'audit_logs_enabled', flag_name: 'Audit Logs Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'b2b_invoicing_enabled', flag_name: 'B2B Invoicing Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'b2b_statements_enabled', flag_name: 'B2B Statements Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'background_jobs_enabled', flag_name: 'Background Jobs Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'backward_stage_transition_allowed', flag_name: 'Backward Stage Transition Allowed', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'basic_reports_enabled', flag_name: 'Basic Reports Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'benchmarking_enabled', flag_name: 'Benchmarking Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'branch_level_user_access', flag_name: 'Branch Level User Access', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'campaigns_enabled', flag_name: 'Campaigns Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'cohort_analysis_enabled', flag_name: 'Cohort Analysis Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'commission_engine_enabled', flag_name: 'Commission Engine Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'configurable_workflows_enabled', flag_name: 'Configurable Workflows Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'consumables_threshold_alerts', flag_name: 'Consumables Threshold Alerts', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_limit', ui_display_order: 0 },
  { flag_key: 'cost_per_order_tracking', flag_name: 'Cost Per Order Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'coupons_enabled', flag_name: 'Coupons Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'credit_notes_enabled', flag_name: 'Credit Notes Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'custom_domain_enabled', flag_name: 'Custom Domain Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_evidence_upload', flag_name: 'Customer Evidence Upload', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'damage_reporting_enabled', flag_name: 'Damage Reporting Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'data_export_enabled', flag_name: 'Data Export Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'delivery_scheduling_enabled', flag_name: 'Delivery Scheduling Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'device_limit_enforced', flag_name: 'Device Limit Enforced', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_limit', ui_display_order: 0 },
  { flag_key: 'dispute_center_enabled', flag_name: 'Dispute Center Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'downtime_analytics_enabled', flag_name: 'Downtime Analytics Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'driver_app_enabled', flag_name: 'Driver App Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'driver_route_optimization', flag_name: 'Driver Route Optimization', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'dunning_enabled', flag_name: 'Dunning Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'dynamic_slot_pricing', flag_name: 'Dynamic Slot Pricing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'eco_badges_enabled', flag_name: 'Eco Badges Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'email_password_login_enabled', flag_name: 'Email Password Login Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'email_provider_enabled', flag_name: 'Email Provider Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'email_receipts_enabled', flag_name: 'Email Receipts Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'emergency_disable_orders', flag_name: 'Emergency Disable Orders', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'emergency_disable_payments', flag_name: 'Emergency Disable Payments', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'escrow_enabled', flag_name: 'Escrow Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'exception_reason_codes_enabled', flag_name: 'Exception Reason Codes Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'export_to_csv_enabled', flag_name: 'Export To Csv Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'express_service_enabled', flag_name: 'Express Service Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'family_accounts_enabled', flag_name: 'Family Accounts Enabled', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'feature_flag_override_hq', flag_name: 'Feature Flag Override Hq', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'franchise_mode_enabled', flag_name: 'Franchise Mode Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'geofence_validation_enabled', flag_name: 'Geofence Validation Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'gift_cards_enabled', flag_name: 'Gift Cards Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'google_maps_enabled', flag_name: 'Google Maps Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'idempotency_enforced', flag_name: 'Idempotency Enforced', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'impersonation_enabled', flag_name: 'Impersonation Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'in_app_receipts_enabled', flag_name: 'In App Receipts Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'intake_barcode_scan_required', flag_name: 'Intake Barcode Scan Required', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'intake_bulk_add_items', flag_name: 'Intake Bulk Add Items', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'intake_label_printing', flag_name: 'Intake Label Printing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'inventory_tracking_enabled', flag_name: 'Inventory Tracking Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'invoice_at_delivery', flag_name: 'Invoice At Delivery', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'invoice_at_ready', flag_name: 'Invoice At Ready', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'invoicing_enabled', flag_name: 'Invoicing Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'issue_to_solve_enabled', flag_name: 'Issue To Solve Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'label_printing_58mm', flag_name: 'Label Printing 58Mm', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'label_printing_80mm', flag_name: 'Label Printing 80Mm', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'live_order_tracking', flag_name: 'Live Order Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'loyalty_points_enabled', flag_name: 'Loyalty Points Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'loyalty_program_enabled', flag_name: 'Loyalty Program Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'loyalty_tiers_enabled', flag_name: 'Loyalty Tiers Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'machine_maintenance_logs', flag_name: 'Machine Maintenance Logs', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'hq_feature', ui_display_order: 0 },
  { flag_key: 'machine_tracking_enabled', flag_name: 'Machine Tracking Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'magic_link_login_enabled', flag_name: 'Magic Link Login Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'maintenance_mode_enabled', flag_name: 'Maintenance Mode Enabled', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'hq_feature', ui_display_order: 0 },
  { flag_key: 'manual_price_override_enabled', flag_name: 'Manual Price Override Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'marketplace_enabled', flag_name: 'Marketplace Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'marketplace_listings_enabled', flag_name: 'Marketplace Listings Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'membership_plans_enabled', flag_name: 'Membership Plans Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'merge_suborders_enabled', flag_name: 'Merge Suborders Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'missing_item_alerts', flag_name: 'Missing Item Alerts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_branch_enabled', flag_name: 'Multi Branch Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_currency_enabled', flag_name: 'Multi Currency Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_tenant_enabled', flag_name: 'Multi Tenant Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_tender_payments', flag_name: 'Multi Tender Payments', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'offline_queue_enabled', flag_name: 'Offline Queue Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_split_enabled', flag_name: 'Order Split Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'otp_login_enabled', flag_name: 'Otp Login Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'otp_proof_of_delivery', flag_name: 'Otp Proof Of Delivery', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'packing_stage_enabled', flag_name: 'Packing Stage Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'partial_delivery_enabled', flag_name: 'Partial Delivery Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'partial_payments_enabled', flag_name: 'Partial Payments Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'partial_release_enabled', flag_name: 'Partial Release Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'pdf_receipts_enabled', flag_name: 'Pdf Receipts Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'photo_capture_on_intake', flag_name: 'Photo Capture On Intake', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'photo_pod_enabled', flag_name: 'Photo Pod Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'pickup_scheduling_enabled', flag_name: 'Pickup Scheduling Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'piece_level_barcode_tracking', flag_name: 'Piece Level Barcode Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'preparation_stage_enabled', flag_name: 'Preparation Stage Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'priority_orders_enabled', flag_name: 'Priority Orders Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'promotional_pricing_rules', flag_name: 'Promotional Pricing Rules', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'qa_mandatory_before_ready', flag_name: 'Qa Mandatory Before Ready', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'qa_photo_on_fail_required', flag_name: 'Qa Photo On Fail Required', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'qa_stage_enabled', flag_name: 'Qa Stage Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'quick_drop_enabled', flag_name: 'Quick Drop Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'quick_drop_without_items', flag_name: 'Quick Drop Without Items', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'rate_limiting_enabled', flag_name: 'Rate Limiting Enabled', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'General', governance_category: 'tenant_limit', ui_display_order: 0 },
  { flag_key: 'rbac_enabled', flag_name: 'Rbac Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'read_only_mode', flag_name: 'Read Only Mode', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'ready_by_estimation_enabled', flag_name: 'Ready By Estimation Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'receipt_branding_enabled', flag_name: 'Receipt Branding Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'referrals_enabled', flag_name: 'Referrals Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'refunds_enabled', flag_name: 'Refunds Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'reprocess_flow_enabled', flag_name: 'Reprocess Flow Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'revenue_heatmaps', flag_name: 'Revenue Heatmaps', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'review_moderation_required', flag_name: 'Review Moderation Required', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sandbox_mode_enabled', flag_name: 'Sandbox Mode Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'scan_enforcement_per_stage', flag_name: 'Scan Enforcement Per Stage', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'session_timeout_control', flag_name: 'Session Timeout Control', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'signature_pod_enabled', flag_name: 'Signature Pod Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'signed_webhooks_only', flag_name: 'Signed Webhooks Only', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sla_dashboards_enabled', flag_name: 'Sla Dashboards Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'slot_capacity_management', flag_name: 'Slot Capacity Management', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sms_provider_enabled', flag_name: 'Sms Provider Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'supplier_management_enabled', flag_name: 'Supplier Management Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'supplier_portal_enabled', flag_name: 'Supplier Portal Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sustainability_metrics_enabled', flag_name: 'Sustainability Metrics Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'thermal_printing_enabled', flag_name: 'Thermal Printing Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'track_individual_pieces', flag_name: 'Track Individual Pieces', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'user_activity_tracking', flag_name: 'User Activity Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'vat_enabled', flag_name: 'Vat Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'verified_reviews_enabled', flag_name: 'Verified Reviews Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'wallet_enabled', flag_name: 'Wallet Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'webhooks_enabled', flag_name: 'Webhooks Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'whatsapp_business_api', flag_name: 'Whatsapp Business Api', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'whatsapp_receipts_enabled', flag_name: 'Whatsapp Receipts Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'white_label_enabled', flag_name: 'White Label Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'workflow_per_service_category', flag_name: 'Workflow Per Service Category', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'workflow_role_restrictions_enabled', flag_name: 'Workflow Role Restrictions Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'General', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'hq_advanced_analytics', flag_name: 'HQ Advanced Analytics', plan_binding_type: 'independent', data_type: 'boolean', default_value: true, ui_group: 'HQ Features', governance_category: 'hq_feature', ui_display_order: 101 },
  { flag_key: 'accounting_integration', flag_name: 'Accounting Integration', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'Integration', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'api_access', flag_name: 'API Access', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Integration', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'pos_integration', flag_name: 'POS Integration', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Integration', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'third_party_integrations', flag_name: 'Third-Party Integrations', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Integration', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'webhooks', flag_name: 'Webhooks', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Integration', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'tenant_max_orders_per_month', flag_name: 'Max Orders Per Month', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 100, ui_group: 'Limits', governance_category: 'tenant_limit', ui_display_order: 30 },
  { flag_key: 'tenant_max_branches', flag_name: 'Max Branches', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 1, ui_group: 'Limits', governance_category: 'tenant_limit', ui_display_order: 31 },
  { flag_key: 'tenant_max_users', flag_name: 'Max Users', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 1, ui_group: 'Limits', governance_category: 'tenant_limit', ui_display_order: 32 },
  { flag_key: 'tenant_max_storage_mb', flag_name: 'Max Storage (MB)', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 1000, ui_group: 'Limits', governance_category: 'tenant_limit', ui_display_order: 33 },
  { flag_key: 'discount_coupons', flag_name: 'Discount Coupons', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'Loyalty', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'loyalty_programs', flag_name: 'Loyalty Programs', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Loyalty', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'points_system', flag_name: 'Points System', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Loyalty', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'referral_program', flag_name: 'Referral Program', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Loyalty', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_portal', flag_name: 'Customer Portal', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Marketplace', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'marketplace_listings', flag_name: 'Marketplace Listings', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Marketplace', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'online_booking', flag_name: 'Online Booking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Marketplace', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'public_catalog', flag_name: 'Public Catalog', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Marketplace', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'customer_app', flag_name: 'Customer Mobile App', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Mobile Apps', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'driver_app', flag_name: 'Driver App', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Mobile Apps', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'mobile_ordering', flag_name: 'Mobile Ordering', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Mobile Apps', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'mobile_tracking', flag_name: 'Mobile Order Tracking', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Mobile Apps', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'store_app', flag_name: 'Store Staff App', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Mobile Apps', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'branch_analytics', flag_name: 'Branch Analytics', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Multi-Location', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'branch_transfers', flag_name: 'Branch Transfers', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Multi-Location', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'centralized_inventory', flag_name: 'Centralized Inventory', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Multi-Location', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'multi_branch', flag_name: 'Multi-Branch', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Multi-Location', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'tenant_multi_branch', flag_name: 'Multi-Branch Support', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Operational Features', governance_category: 'tenant_feature', ui_display_order: 10 },
  { flag_key: 'tenant_driver_app', flag_name: 'Driver App Access', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Operational Features', governance_category: 'tenant_feature', ui_display_order: 11 },
  { flag_key: 'tenant_white_label', flag_name: 'White Label Branding', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Operational Features', governance_category: 'tenant_feature', ui_display_order: 12 },
  { flag_key: 'bulk_order_import', flag_name: 'Bulk Order Import', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Order Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_notes', flag_name: 'Order Notes & Instructions', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Order Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_scheduling', flag_name: 'Order Scheduling', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Order Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'order_templates', flag_name: 'Order Templates', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Order Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'quick_drop_orders', flag_name: 'Quick Drop Orders', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Order Management', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'b2b_contracts', flag_name: 'B2B Contracts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'b2b_invoicing', flag_name: 'B2B Invoicing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'credit_limits', flag_name: 'Credit Limits', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 0, ui_group: 'Payment & Billing', governance_category: 'tenant_limit', ui_display_order: 0 },
  { flag_key: 'online_payments', flag_name: 'Online Payment Processing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'partial_payments', flag_name: 'Partial Payments', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'payment_gateway_hyperpay', flag_name: 'HyperPay Integration', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'payment_gateway_paytabs', flag_name: 'PayTabs Integration', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'payment_gateway_stripe', flag_name: 'Stripe Integration', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'payment_plans', flag_name: 'Payment Plans', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'pdf_invoices', flag_name: 'PDF Invoices', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Payment & Billing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'hq_maintenance_mode', flag_name: 'Maintenance Mode', plan_binding_type: 'independent', data_type: 'boolean', default_value: false, ui_group: 'Platform Config', governance_category: 'hq_config', ui_display_order: 100 },
  { flag_key: 'invoice_printing', flag_name: 'Invoice Printing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Printing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'label_printing', flag_name: 'Label Printing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Printing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'packing_list_printing', flag_name: 'Packing List Printing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Printing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'printing', flag_name: 'Receipt Printing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Printing', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'digital_receipts', flag_name: 'Digital Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Receipts', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'in_app_receipts', flag_name: 'In-App Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Receipts', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'receipt_history', flag_name: 'Receipt History', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Receipts', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'audit_logs', flag_name: 'Audit Logs', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Security', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'data_encryption', flag_name: 'Data Encryption', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Security', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'gdpr_compliance', flag_name: 'GDPR Compliance', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Security', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'two_factor_auth', flag_name: 'Two-Factor Authentication', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Security', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'service_preferences_enabled', flag_name: 'Service Preferences Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 1 },
  { flag_key: 'packing_preferences_enabled', flag_name: 'Packing Preferences Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 2 },
  { flag_key: 'per_piece_packing', flag_name: 'Per-Piece Packing', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 3 },
  { flag_key: 'per_piece_service_prefs', flag_name: 'Per-Piece Service Prefs', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 4 },
  { flag_key: 'customer_standing_prefs', flag_name: 'Customer Standing Prefs', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 5 },
  { flag_key: 'bundles_enabled', flag_name: 'Preference Bundles Enabled', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 6 },
  { flag_key: 'smart_suggestions', flag_name: 'Smart Suggestions', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 7 },
  { flag_key: 'sla_adjustment', flag_name: 'SLA Adjustment', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 8 },
  { flag_key: 'repeat_last_order', flag_name: 'Repeat Last Order', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 9 },
  { flag_key: 'processing_confirmation', flag_name: 'Processing Confirmation', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Service Preferences', governance_category: 'tenant_feature', ui_display_order: 10 },
  { flag_key: 'max_service_prefs_per_item', flag_name: 'Max Service Prefs Per Item', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 10, ui_group: 'Service Preferences', governance_category: 'tenant_limit', ui_display_order: 11 },
  { flag_key: 'max_service_prefs_per_piece', flag_name: 'Max Service Prefs Per Piece', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 5, ui_group: 'Service Preferences', governance_category: 'tenant_limit', ui_display_order: 12 },
  { flag_key: 'max_bundles', flag_name: 'Max Bundles', plan_binding_type: 'plan_bound', data_type: 'integer', default_value: 5, ui_group: 'Service Preferences', governance_category: 'tenant_limit', ui_display_order: 13 },
  { flag_key: 'branded_emails', flag_name: 'Branded Emails', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'White Label', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'branded_receipts', flag_name: 'Branded Receipts', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'White Label', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'custom_branding', flag_name: 'Custom Branding', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'White Label', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'custom_domain', flag_name: 'Custom Domain', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'White Label', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'white_label', flag_name: 'White Label', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'White Label', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'assembly_workflow', flag_name: 'Assembly Workflow', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'custom_workflows', flag_name: 'Custom Workflows', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'intake_workflow', flag_name: 'Intake Workflow', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'packing_workflow', flag_name: 'Packing Workflow', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'preparation_workflow', flag_name: 'Preparation Workflow', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'qa_workflow', flag_name: 'Quality Assurance', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'sorting_workflow', flag_name: 'Sorting Workflow', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 },
  { flag_key: 'workflow_automation', flag_name: 'Workflow Automation', plan_binding_type: 'plan_bound', data_type: 'boolean', default_value: false, ui_group: 'Workflow', governance_category: 'tenant_feature', ui_display_order: 0 }
];

// ========================
// Derived: Keys
// ========================

/**
 * Named constants for ALL flag keys — avoids hardcoded strings, reduces typos.
 * Usage: flags[FLAG_KEYS.B2B_CONTRACTS] instead of flags['b2b_contracts']
 * Derived from FLAG_CATALOG; constant name = flag_key in UPPER_SNAKE_CASE.
 */
export const FLAG_KEYS = Object.fromEntries(
  FLAG_CATALOG.map((e) => [e.flag_key.toUpperCase(), e.flag_key])
) as Record<string, string>;

/** Type for any flag key string (all catalog keys) */
export type FlagKey = (typeof FLAG_CATALOG)[number]['flag_key'];

/** Named constants for common flag keys (RequireFeature, useFeature) — subset of FLAG_KEYS */
export const FEATURE_FLAG_KEYS = {
  PDF_INVOICES: 'pdf_invoices',
  WHATSAPP_RECEIPTS: 'whatsapp_receipts',
  IN_APP_RECEIPTS: 'in_app_receipts',
  PRINTING: 'printing',
  B2B_CONTRACTS: 'b2b_contracts',
  WHITE_LABEL: 'white_label',
  MARKETPLACE_LISTINGS: 'marketplace_listings',
  LOYALTY_PROGRAMS: 'loyalty_programs',
  DRIVER_APP: 'driver_app',
  MULTI_BRANCH: 'multi_branch',
  ADVANCED_ANALYTICS: 'advanced_analytics',
  API_ACCESS: 'api_access',
  // addeb by jehad
  
    TENANT_NEW_DASHBOARD_UI: 'tenant_new_dashboard_ui',
    TENANT_BETA_AI_CLASSIFICATION: 'tenant_beta_ai_classification',
    TENANT_BETA_VOICE_ORDERS: 'tenant_beta_voice_orders',
    HQ_MAINTENANCE_MODE: 'hq_maintenance_mode',
    MAINTENANCE_MODE_ENABLED: 'maintenance_mode_enabled',
    HQ_ADVANCED_ANALYTICS: 'hq_advanced_analytics',
    MACHINE_MAINTENANCE_LOGS: 'machine_maintenance_logs',
    TENANT_API_ACCESS: 'tenant_api_access',
    WORKFLOW_ROLE_RESTRICTIONS_ENABLED: 'workflow_role_restrictions_enabled',
    TENANT_WHATSAPP_RECEIPTS: 'tenant_whatsapp_receipts',
    TENANT_IN_APP_RECEIPTS: 'tenant_in_app_receipts',
    TENANT_MULTI_BRANCH: 'tenant_multi_branch',
    TENANT_DRIVER_APP: 'tenant_driver_app',
    TENANT_WHITE_LABEL: 'tenant_white_label',
    TENANT_ADVANCED_ANALYTICS: 'tenant_advanced_analytics',
    ERP_LITE_ENABLED: 'erp_lite_enabled',
    ERP_LITE_GL_ENABLED: 'erp_lite_gl_enabled',
    ERP_LITE_REPORTS_ENABLED: 'erp_lite_reports_enabled',
    ERP_LITE_AR_ENABLED: 'erp_lite_ar_enabled',
    ERP_LITE_EXPENSES_ENABLED: 'erp_lite_expenses_enabled',
    ERP_LITE_BANK_RECON_ENABLED: 'erp_lite_bank_recon_enabled',
    ERP_LITE_AP_ENABLED: 'erp_lite_ap_enabled',
    ERP_LITE_PO_ENABLED: 'erp_lite_po_enabled',
    ERP_LITE_BRANCH_PL_ENABLED: 'erp_lite_branch_pl_enabled',
    ERP_LITE_READINESS_ENABLED: 'erp_lite_readiness_enabled',
    ERP_LITE_USAGE_MAP_ENABLED: 'erp_lite_usage_map_enabled',
    ERP_LITE_EXCEPTIONS_ENABLED: 'erp_lite_exceptions_enabled',
    ERP_LITE_PERIODS_ENABLED: 'erp_lite_periods_enabled',
    ERP_LITE_POST_AUDIT_ENABLED: 'erp_lite_post_audit_enabled',
    WALLET_ENABLED: 'wallet_enabled',
    WEBHOOKS: 'webhooks',
    WEBHOOKS_ENABLED: 'webhooks_enabled',
    WHATSAPP_BUSINESS_API: 'whatsapp_business_api',
    WHATSAPP_NOTIFICATIONS: 'whatsapp_notifications',
    WHATSAPP_RECEIPTS_ENABLED: 'whatsapp_receipts_enabled',
    WHITE_LABEL_ENABLED: 'white_label_enabled',
    WORKFLOW_AUTOMATION: 'workflow_automation',
    WORKFLOW_PER_SERVICE_CATEGORY: 'workflow_per_service_category',
    TENANT_PDF_INVOICES: 'tenant_pdf_invoices',
    TENANT_CUSTOM_DOMAIN: 'tenant_custom_domain',
    TENANT_BRANDING_CONFIG: 'tenant_branding_config',
    SMART_SUGGESTIONS: 'smart_suggestions',
    PROCESSING_CONFIRMATION: 'processing_confirmation',
    SERVICE_PREFERENCES_ENABLED: 'service_preferences_enabled',
    PACKING_PREFERENCES_ENABLED: 'packing_preferences_enabled',
    PER_PIECE_PACKING: 'per_piece_packing',
    PER_PIECE_SERVICE_PREFS: 'per_piece_service_prefs',
    CUSTOMER_STANDING_PREFS: 'customer_standing_prefs',
    BUNDLES_ENABLED: 'bundles_enabled',
    REPEAT_LAST_ORDER: 'repeat_last_order',
    SLA_ADJUSTMENT: 'sla_adjustment',
    ACCOUNTING_EXPORT_ENABLED: 'accounting_export_enabled',
    ACCOUNTING_INTEGRATION: 'accounting_integration',
    ADDRESS_MANAGEMENT: 'address_management',
    AUDIT_LOGS: 'audit_logs',
    ADVANCE_PAYMENTS_ENABLED: 'advance_payments_enabled',
    ADVANCED_ANALYTICS_ENABLED: 'advanced_analytics_enabled',
    ADVANCED_ROLES_ENABLED: 'advanced_roles_enabled',
    AI_CHURN_PREDICTION: 'ai_churn_prediction',
    AI_DAMAGE_DETECTION: 'ai_damage_detection',
    AI_FEATURES_EXPLAINABLE_ONLY: 'ai_features_explainable_only',
    AI_FEEDBACK_CAPTURE: 'ai_feedback_capture',
    AI_PRICING_ESTIMATOR: 'ai_pricing_estimator',
    AI_READY_BY_PREDICTION: 'ai_ready_by_prediction',
    AI_RECOMMENDATIONS_ENABLED: 'ai_recommendations_enabled',
    AI_ROUTING_ETA: 'ai_routing_eta',
    AI_VISION_QA: 'ai_vision_qa',
    API_ACCESS_ENABLED: 'api_access_enabled',
    APPROVAL_REQUIRED_FOR_REFUNDS: 'approval_required_for_refunds',
    ASSEMBLY_BIN_LOCATION_TRACKING: 'assembly_bin_location_tracking',
    ASSEMBLY_COMPLETENESS_CHECK: 'assembly_completeness_check',
    ASSEMBLY_STAGE_ENABLED: 'assembly_stage_enabled',
    ASSEMBLY_WORKFLOW: 'assembly_workflow',
    AUDIT_LOGS_ENABLED: 'audit_logs_enabled',
    B2B_INVOICING: 'b2b_invoicing',
    B2B_INVOICING_ENABLED: 'b2b_invoicing_enabled',
    B2B_STATEMENTS_ENABLED: 'b2b_statements_enabled',
    BACKGROUND_JOBS_ENABLED: 'background_jobs_enabled',
    BACKWARD_STAGE_TRANSITION_ALLOWED: 'backward_stage_transition_allowed',
    BARCODE_SCANNING: 'barcode_scanning',
    BASIC_REPORTS_ENABLED: 'basic_reports_enabled',
    BENCHMARKING_ENABLED: 'benchmarking_enabled',
    BRANCH_ANALYTICS: 'branch_analytics',
    BRANCH_LEVEL_USER_ACCESS: 'branch_level_user_access',
    BRANCH_TRANSFERS: 'branch_transfers',
    BRANDED_EMAILS: 'branded_emails',
    BRANDED_RECEIPTS: 'branded_receipts',
    BULK_ORDER_IMPORT: 'bulk_order_import',
    BULK_PRICING: 'bulk_pricing',
    CAMPAIGNS_ENABLED: 'campaigns_enabled',
    CENTRALIZED_INVENTORY: 'centralized_inventory',
    COHORT_ANALYSIS_ENABLED: 'cohort_analysis_enabled',
    COMMISSION_ENGINE_ENABLED: 'commission_engine_enabled',
    CONFIGURABLE_WORKFLOWS_ENABLED: 'configurable_workflows_enabled',
    COST_PER_ORDER_TRACKING: 'cost_per_order_tracking',
    COUPONS_ENABLED: 'coupons_enabled',
    CREDIT_NOTES_ENABLED: 'credit_notes_enabled',
    CUSTOM_BRANDING: 'custom_branding',
    CUSTOM_DOMAIN: 'custom_domain',
    CUSTOM_DOMAIN_ENABLED: 'custom_domain_enabled',
    CUSTOM_REPORTS: 'custom_reports',
    CUSTOM_WORKFLOWS: 'custom_workflows',
    CUSTOMER_ANALYTICS: 'customer_analytics',
    CUSTOMER_APP: 'customer_app',
    CUSTOMER_EVIDENCE_UPLOAD: 'customer_evidence_upload',
    CUSTOMER_HISTORY: 'customer_history',
    CUSTOMER_NOTES: 'customer_notes',
    CUSTOMER_PORTAL: 'customer_portal',
    CUSTOMER_PROFILES: 'customer_profiles',
    CUSTOMER_SEGMENTS: 'customer_segments',
    CUSTOMER_TAGS: 'customer_tags',
    DAMAGE_REPORTING_ENABLED: 'damage_reporting_enabled',
    DATA_ENCRYPTION: 'data_encryption',
    DATA_EXPORT_ENABLED: 'data_export_enabled',
    DELIVERY_OPTIMIZATION: 'delivery_optimization',
    DELIVERY_SCHEDULING: 'delivery_scheduling',
    DELIVERY_SCHEDULING_ENABLED: 'delivery_scheduling_enabled',
    DELIVERY_TRACKING: 'delivery_tracking',
    DELIVERY_ZONES: 'delivery_zones',
    DIGITAL_RECEIPTS: 'digital_receipts',
    DISCOUNT_COUPONS: 'discount_coupons',
    DISPUTE_CENTER_ENABLED: 'dispute_center_enabled',
    DOWNTIME_ANALYTICS_ENABLED: 'downtime_analytics_enabled',
    DRIVER_APP_ENABLED: 'driver_app_enabled',
    DRIVER_ASSIGNMENT: 'driver_assignment',
    DRIVER_ROUTE_OPTIMIZATION: 'driver_route_optimization',
    DUNNING_ENABLED: 'dunning_enabled',
    DYNAMIC_SLOT_PRICING: 'dynamic_slot_pricing',
    ECO_BADGES_ENABLED: 'eco_badges_enabled',
    EMAIL_PASSWORD_LOGIN_ENABLED: 'email_password_login_enabled',
    EMAIL_PROVIDER_ENABLED: 'email_provider_enabled',
    EMAIL_RECEIPTS: 'email_receipts',
    EMAIL_RECEIPTS_ENABLED: 'email_receipts_enabled',
    EMERGENCY_DISABLE_ORDERS: 'emergency_disable_orders',
    EMERGENCY_DISABLE_PAYMENTS: 'emergency_disable_payments',
    ESCROW_ENABLED: 'escrow_enabled',
    EXCEPTION_REASON_CODES_ENABLED: 'exception_reason_codes_enabled',
    EXPORT_REPORTS: 'export_reports',
    EXPORT_TO_CSV_ENABLED: 'export_to_csv_enabled',
    EXPRESS_SERVICE_ENABLED: 'express_service_enabled',
    FAMILY_ACCOUNTS_ENABLED: 'family_accounts_enabled',
    FEATURE_FLAG_OVERRIDE_HQ: 'feature_flag_override_hq',
    FRANCHISE_MODE_ENABLED: 'franchise_mode_enabled',
    GDPR_COMPLIANCE: 'gdpr_compliance',
    GEOFENCE_VALIDATION_ENABLED: 'geofence_validation_enabled',
    GIFT_CARDS_ENABLED: 'gift_cards_enabled',
    GOOGLE_MAPS_ENABLED: 'google_maps_enabled',
    IDEMPOTENCY_ENFORCED: 'idempotency_enforced',
    IMAGE_RECOGNITION: 'image_recognition',
    IMPERSONATION_ENABLED: 'impersonation_enabled',
    IN_APP_RECEIPTS_ENABLED: 'in_app_receipts_enabled',
    INTAKE_BARCODE_SCAN_REQUIRED: 'intake_barcode_scan_required',
    INTAKE_BULK_ADD_ITEMS: 'intake_bulk_add_items',
    INTAKE_LABEL_PRINTING: 'intake_label_printing',
    INTAKE_WORKFLOW: 'intake_workflow',
    INVENTORY_TRACKING_ENABLED: 'inventory_tracking_enabled',
    INVOICE_AT_DELIVERY: 'invoice_at_delivery',
    INVOICE_AT_READY: 'invoice_at_ready',
    INVOICE_PRINTING: 'invoice_printing',
    INVOICING_ENABLED: 'invoicing_enabled',
    ISSUE_TO_SOLVE_ENABLED: 'issue_to_solve_enabled',
    LABEL_PRINTING: 'label_printing',
    LABEL_PRINTING_58MM: 'label_printing_58mm',
    LABEL_PRINTING_80MM: 'label_printing_80mm',
    LIVE_ORDER_TRACKING: 'live_order_tracking',
    LOYALTY_POINTS_ENABLED: 'loyalty_points_enabled',
    LOYALTY_PROGRAM_ENABLED: 'loyalty_program_enabled',
    LOYALTY_TIERS_ENABLED: 'loyalty_tiers_enabled',
    MACHINE_TRACKING_ENABLED: 'machine_tracking_enabled',
    MAGIC_LINK_LOGIN_ENABLED: 'magic_link_login_enabled',
    MANUAL_PRICE_OVERRIDE_ENABLED: 'manual_price_override_enabled',
    MARKETPLACE_ENABLED: 'marketplace_enabled',
    POINTS_SYSTEM: 'points_system',
    MARKETPLACE_LISTINGS_ENABLED: 'marketplace_listings_enabled',
    MEMBERSHIP_PLANS_ENABLED: 'membership_plans_enabled',
    MERGE_SUBORDERS_ENABLED: 'merge_suborders_enabled',
    MISSING_ITEM_ALERTS: 'missing_item_alerts',
    MOBILE_ORDERING: 'mobile_ordering',
    MOBILE_TRACKING: 'mobile_tracking',
    MULTI_BRANCH_ENABLED: 'multi_branch_enabled',
    MULTI_CURRENCY_ENABLED: 'multi_currency_enabled',
    MULTI_LANGUAGE: 'multi_language',
    MULTI_TENANT_ENABLED: 'multi_tenant_enabled',
    MULTI_TENDER_PAYMENTS: 'multi_tender_payments',
    OFFLINE_QUEUE_ENABLED: 'offline_queue_enabled',
    ONLINE_BOOKING: 'online_booking',
    ONLINE_PAYMENTS: 'online_payments',
    ORDER_ANALYTICS: 'order_analytics',
    ORDER_NOTES: 'order_notes',
    ORDER_REMINDERS: 'order_reminders',
    ORDER_SCHEDULING: 'order_scheduling',
    ORDER_SPLIT_ENABLED: 'order_split_enabled',
    ORDER_TEMPLATES: 'order_templates',
    OTP_LOGIN_ENABLED: 'otp_login_enabled',
    OTP_PROOF_OF_DELIVERY: 'otp_proof_of_delivery',
    PACKING_LIST_PRINTING: 'packing_list_printing',
    PACKING_STAGE_ENABLED: 'packing_stage_enabled',
    PACKING_WORKFLOW: 'packing_workflow',
    PARTIAL_DELIVERY_ENABLED: 'partial_delivery_enabled',
    PARTIAL_PAYMENTS: 'partial_payments',
    PARTIAL_PAYMENTS_ENABLED: 'partial_payments_enabled',
    PARTIAL_RELEASE_ENABLED: 'partial_release_enabled',
    PAYMENT_GATEWAY_HYPERPAY: 'payment_gateway_hyperpay',
    PAYMENT_GATEWAY_PAYTABS: 'payment_gateway_paytabs',
    PAYMENT_GATEWAY_STRIPE: 'payment_gateway_stripe',
    PAYMENT_PLANS: 'payment_plans',
    PDF_RECEIPTS_ENABLED: 'pdf_receipts_enabled',
    PERFORMANCE_DASHBOARD: 'performance_dashboard',
    PHOTO_CAPTURE_ON_INTAKE: 'photo_capture_on_intake',
    PHOTO_POD_ENABLED: 'photo_pod_enabled',
    PICKUP_SCHEDULING_ENABLED: 'pickup_scheduling_enabled',
    PIECE_LEVEL_BARCODE_TRACKING: 'piece_level_barcode_tracking',
    POS_INTEGRATION: 'pos_integration',
    PREPARATION_STAGE_ENABLED: 'preparation_stage_enabled',
    PREPARATION_WORKFLOW: 'preparation_workflow',
    PRICING_RULES: 'pricing_rules',
    PRIORITY_ORDERS_ENABLED: 'priority_orders_enabled',
    PRODUCT_VARIANTS: 'product_variants',
    PROMOTIONAL_PRICING_RULES: 'promotional_pricing_rules',
    PUBLIC_CATALOG: 'public_catalog',
    PUSH_NOTIFICATIONS: 'push_notifications',
    QA_MANDATORY_BEFORE_READY: 'qa_mandatory_before_ready',
    QA_PHOTO_ON_FAIL_REQUIRED: 'qa_photo_on_fail_required',
    QA_STAGE_ENABLED: 'qa_stage_enabled',
    QA_WORKFLOW: 'qa_workflow',
    QR_CODE_GENERATION: 'qr_code_generation',
    QUICK_DROP_ENABLED: 'quick_drop_enabled',
    QUICK_DROP_ORDERS: 'quick_drop_orders',
    QUICK_DROP_WITHOUT_ITEMS: 'quick_drop_without_items',
    RBAC_ENABLED: 'rbac_enabled',
    READ_ONLY_MODE: 'read_only_mode',
    READY_BY_ESTIMATION_ENABLED: 'ready_by_estimation_enabled',
    RECEIPT_BRANDING_ENABLED: 'receipt_branding_enabled',
    RECEIPT_HISTORY: 'receipt_history',
    REFERRAL_PROGRAM: 'referral_program',
    REFERRALS_ENABLED: 'referrals_enabled',
    REFUNDS_ENABLED: 'refunds_enabled',
    REPROCESS_FLOW_ENABLED: 'reprocess_flow_enabled',
    REVENUE_ANALYTICS: 'revenue_analytics',
    REVENUE_HEATMAPS: 'revenue_heatmaps',
    REVIEW_MODERATION_REQUIRED: 'review_moderation_required',
    RTL_SUPPORT: 'rtl_support',
    SANDBOX_MODE_ENABLED: 'sandbox_mode_enabled',
    SCAN_ENFORCEMENT_PER_STAGE: 'scan_enforcement_per_stage',
    SERVICE_CATALOG: 'service_catalog',
    SERVICE_CATEGORIES: 'service_categories',
    SESSION_TIMEOUT_CONTROL: 'session_timeout_control',
    SIGNATURE_POD_ENABLED: 'signature_pod_enabled',
    SIGNED_WEBHOOKS_ONLY: 'signed_webhooks_only',
    SLA_DASHBOARDS_ENABLED: 'sla_dashboards_enabled',
    SLOT_CAPACITY_MANAGEMENT: 'slot_capacity_management',
    SMS_NOTIFICATIONS: 'sms_notifications',
    SMS_PROVIDER_ENABLED: 'sms_provider_enabled',
    SORTING_WORKFLOW: 'sorting_workflow',
    STORE_APP: 'store_app',
    SUPPLIER_MANAGEMENT_ENABLED: 'supplier_management_enabled',
    SUPPLIER_PORTAL_ENABLED: 'supplier_portal_enabled',
    SUSTAINABILITY_METRICS_ENABLED: 'sustainability_metrics_enabled',
    VAT_ENABLED: 'vat_enabled',
    THERMAL_PRINTING_ENABLED: 'thermal_printing_enabled',
    THIRD_PARTY_INTEGRATIONS: 'third_party_integrations',
    TRACK_INDIVIDUAL_PIECES: 'track_individual_pieces',
    TWO_FACTOR_AUTH: 'two_factor_auth',
    USER_ACTIVITY_TRACKING: 'user_activity_tracking',
    VERIFIED_REVIEWS_ENABLED: 'verified_reviews_enabled',
    TENANT_MAX_STORAGE_MB: 'tenant_max_storage_mb',
    TENANT_MAX_USERS: 'tenant_max_users',
    DEVICE_LIMIT_ENFORCED: 'device_limit_enforced',
    ASSEMBLY_CAPACITY_LIMITS: 'assembly_capacity_limits',
    CREDIT_LIMITS: 'credit_limits',
    CONSUMABLES_THRESHOLD_ALERTS: 'consumables_threshold_alerts',
    MAX_SERVICE_PREFS_PER_ITEM: 'max_service_prefs_per_item',
    MAX_SERVICE_PREFS_PER_PIECE: 'max_service_prefs_per_piece',
    MAX_BUNDLES: 'max_bundles',
    RATE_LIMITING_ENABLED: 'rate_limiting_enabled',
    TENANT_MAX_BRANCHES: 'tenant_max_branches',
    TENANT_MAX_ORDERS_PER_MONTH: 'tenant_max_orders_per_month',
  
} as const satisfies Record<string, FlagKey>;
//as const satisfies Record<string, FeatureFlagKey>;

/** All flag keys for batch RPC (hq_ff_get_effective_values_batch) */
export const ALL_FLAG_KEYS = FLAG_CATALOG.map((e) => e.flag_key);

export const FLAG_KEYS_PLAN_BOUND = FLAG_CATALOG.filter(
  (e) => e.plan_binding_type === 'plan_bound'
).map((e) => e.flag_key);

export const FLAG_KEYS_INDEPENDENT = FLAG_CATALOG.filter(
  (e) => e.plan_binding_type === 'independent'
).map((e) => e.flag_key);

// ========================
// Derived: Defaults
// ========================

export const DEFAULT_FEATURE_FLAGS: Record<string, TenantSettingDefaultValue> = Object.fromEntries(
  FLAG_CATALOG.map((e) => [e.flag_key, e.default_value])
);

export const DEFAULT_PLAN_BOUND_FEATURE_FLAGS: Record<string, TenantSettingDefaultValue> =
  Object.fromEntries(
    FLAG_CATALOG.filter((e) => e.plan_binding_type === 'plan_bound').map((e) => [
      e.flag_key,
      e.default_value,
    ])
  );

export const DEFAULT_INDEPENDENT_FEATURE_FLAGS: Record<string, TenantSettingDefaultValue> =
  Object.fromEntries(
    FLAG_CATALOG.filter((e) => e.plan_binding_type === 'independent').map((e) => [
      e.flag_key,
      e.default_value,
    ])
  );
