/**
 * Workflow action codes — mirror `sys_wf_actions_cd.action_code` (DB-mirror rule).
 *
 * Used by the workflow engine, API routes, and UI action CTAs.
 * @see docs/features/Workflow_Order_Advance/04_Status_and_Vocabulary.md
 */

export const WORKFLOW_ACTIONS = {
  CONFIRM_PHYSICAL_INTAKE: 'CONFIRM_PHYSICAL_INTAKE',
  SEND_TO_PREPARATION: 'SEND_TO_PREPARATION',
  COMPLETE_PREPARATION: 'COMPLETE_PREPARATION',
  COMPLETE_PROCESSING: 'COMPLETE_PROCESSING',
  COMPLETE_ASSEMBLY: 'COMPLETE_ASSEMBLY',
  PASS_QA: 'PASS_QA',
  FAIL_QA: 'FAIL_QA',
  COMPLETE_PACKING: 'COMPLETE_PACKING',
  MARK_READY: 'MARK_READY',
  RELEASE_FOR_PICKUP: 'RELEASE_FOR_PICKUP',
  CONFIRM_PICKUP: 'CONFIRM_PICKUP',
  RELEASE_FOR_DELIVERY: 'RELEASE_FOR_DELIVERY',
  CONFIRM_DELIVERY: 'CONFIRM_DELIVERY',
  ASSIGN_HOME_COLLECTION: 'ASSIGN_HOME_COLLECTION',
  CONFIRM_HOME_COLLECTION: 'CONFIRM_HOME_COLLECTION',
  FAIL_HOME_COLLECTION: 'FAIL_HOME_COLLECTION',
  CANCEL_ORDER: 'CANCEL_ORDER',
  RETURN_ORDER: 'RETURN_ORDER',
  HOLD_ORDER_WORK: 'HOLD_ORDER_WORK',
  RESUME_ORDER_WORK: 'RESUME_ORDER_WORK',
  STOP_ORDER_WORK: 'STOP_ORDER_WORK',
} as const;

export type WorkflowActionCode = (typeof WORKFLOW_ACTIONS)[keyof typeof WORKFLOW_ACTIONS];

/** Idempotency resource namespace for POST …/actions. */
export const WORKFLOW_ACTION_IDEMPOTENCY_RESOURCE = 'workflow_action' as const;
