/**
 * Supabase Database types.
 * Supabase project is at repo root: supabase/ (from cmx-api: ../supabase).
 * Generate: cd ../supabase && supabase gen types typescript --local > ../cmx-api/src/supabase/types.ts
 * Do not edit this file manually when using generated types.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
