-- =========================================================
-- CleanMateX Payment / Settlement Catalogs Target Schema v1.1
-- Reference target only. Inspect current schema before migration.
-- =========================================================

-- 1. Real payment methods only
create table if not exists public.sys_payment_method_cd (
  payment_method_code varchar(50) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  payment_method_family varchar(50) not null,
  payment_nature varchar(50) not null default 'REAL_PAYMENT',
  is_cash boolean not null default false,
  is_card boolean not null default false,
  is_bank boolean not null default false,
  is_check boolean not null default false,
  is_mobile boolean not null default false,
  is_gateway boolean not null default false,
  is_digital boolean not null default false,
  requires_cash_drawer boolean not null default false,
  requires_reference boolean not null default false,
  requires_external_confirmation boolean not null default false,
  supports_authorization boolean not null default false,
  supports_capture boolean not null default false,
  supports_refund boolean not null default true,
  supports_void boolean not null default false,
  supports_partial_payment boolean not null default true,
  allowed_for_order_payment boolean not null default true,
  allowed_for_invoice_payment boolean not null default true,
  allowed_for_refund boolean not null default true,
  allowed_for_customer_advance boolean not null default true,
  allowed_for_wallet_topup boolean not null default true,
  allowed_for_gift_card_topup boolean not null default true,
  allowed_for_supplier_payment boolean not null default false,
  allowed_for_expense_payment boolean not null default false,
  display_order int null,
  icon text null,
  color varchar(30) null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_payment_method_nature check (payment_nature in ('REAL_PAYMENT')),
  constraint chk_sys_payment_method_family check (payment_method_family in ('CASH','CARD','BANK','CHECK','MOBILE','GATEWAY','DIGITAL','OTHER'))
);
comment on table public.sys_payment_method_cd is 'Global HQ catalog of real payment channels only. Gift card, wallet, customer advance, credit note, and customer credit are credit application types, not real payment methods.';

-- 2. Tenant payment method configuration
create table if not exists public.org_payment_methods_cf (
  id uuid not null default gen_random_uuid(),
  tenant_org_id uuid not null,
  branch_id uuid null,
  payment_method_code varchar(50) not null,
  gateway_code varchar(50) null,
  display_name text null,
  display_name2 text null,
  description text null,
  description2 text null,
  is_enabled boolean not null default true,
  is_default boolean not null default false,
  allowed_in_pos boolean not null default true,
  allowed_in_customer_app boolean not null default false,
  allowed_in_admin boolean not null default true,
  allowed_in_driver_app boolean not null default false,
  allowed_for_order_payment boolean not null default true,
  allowed_for_invoice_payment boolean not null default true,
  allowed_for_refund boolean not null default true,
  allowed_for_customer_advance boolean not null default true,
  allowed_for_wallet_topup boolean not null default true,
  allowed_for_gift_card_topup boolean not null default true,
  allowed_for_supplier_payment boolean not null default false,
  allowed_for_expense_payment boolean not null default false,
  requires_cash_drawer boolean null,
  requires_reference boolean null,
  requires_approval boolean not null default false,
  supports_partial_payment boolean not null default true,
  supports_overpayment boolean not null default false,
  supports_change_return boolean not null default false,
  min_amount numeric(19,4) null,
  max_amount numeric(19,4) null,
  supported_currencies text[] null,
  fee_percentage numeric(9,6) null,
  fee_fixed_amount numeric(19,4) null,
  display_order int null,
  metadata jsonb not null default '{}'::jsonb,
  rec_status smallint not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(120) null,
  updated_at timestamptz null,
  updated_by varchar(120) null,
  constraint pk_org_payment_methods_cf primary key (id, tenant_org_id),
  constraint uq_org_payment_methods_cf_method_branch unique (tenant_org_id, branch_id, payment_method_code),
  constraint fk_org_payment_methods_cf_sys_method foreign key (payment_method_code) references public.sys_payment_method_cd(payment_method_code)
);
comment on table public.org_payment_methods_cf is 'Tenant/branch/channel-level configuration for real payment methods from sys_payment_method_cd.';

-- 3. Financial direction catalog
create table if not exists public.sys_fin_direction_cd (
  direction_code varchar(20) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  affects_cash_in boolean not null default false,
  affects_cash_out boolean not null default false,
  is_neutral boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

-- 4. Voucher line type catalog
create table if not exists public.sys_fin_voucher_line_type_cd (
  line_type varchar(50) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  default_direction varchar(20) not null,
  affects_cash_or_bank boolean not null default false,
  affects_credit_balance boolean not null default false,
  affects_ar boolean not null default false,
  affects_expense boolean not null default false,
  allows_payment_method boolean not null default false,
  allows_credit_application_type boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_fin_voucher_line_type_direction check (default_direction in ('IN','OUT','NEUTRAL'))
);

-- 5. Voucher target type catalog
create table if not exists public.sys_fin_voucher_target_type_cd (
  target_type varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  target_table text null,
  requires_target_id boolean not null default true,
  affects_order boolean not null default false,
  affects_ar_invoice boolean not null default false,
  affects_b2b_statement boolean not null default false,
  affects_wallet boolean not null default false,
  affects_gift_card boolean not null default false,
  affects_customer_advance boolean not null default false,
  affects_customer_credit boolean not null default false,
  affects_supplier boolean not null default false,
  affects_expense boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

-- 6. Voucher line role catalog
create table if not exists public.sys_fin_voucher_line_role_cd (
  line_role varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  default_line_type varchar(50) not null,
  default_target_type varchar(80) not null,
  default_direction varchar(20) not null,
  creates_order_payment boolean not null default false,
  creates_order_credit_application boolean not null default false,
  creates_invoice_payment boolean not null default false,
  creates_invoice_credit_application boolean not null default false,
  creates_statement_payment boolean not null default false,
  creates_statement_credit_application boolean not null default false,
  creates_wallet_ledger boolean not null default false,
  creates_gift_card_ledger boolean not null default false,
  creates_customer_advance_ledger boolean not null default false,
  creates_customer_credit_ledger boolean not null default false,
  creates_supplier_payment boolean not null default false,
  creates_expense_payment boolean not null default false,
  creates_cash_drawer_movement boolean not null default false,
  creates_refund_effect boolean not null default false,
  requires_payment_method boolean not null default false,
  requires_credit_application_type boolean not null default false,
  requires_target_id boolean not null default true,
  requires_source_reference boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint fk_sys_fin_voucher_line_role_type foreign key (default_line_type) references public.sys_fin_voucher_line_type_cd(line_type),
  constraint chk_sys_fin_voucher_line_role_direction check (default_direction in ('IN','OUT','NEUTRAL'))
);

-- 7. Voucher source type catalog - v1.1
create table if not exists public.sys_fin_voucher_source_type_cd (
  source_type varchar(100) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  source_family varchar(60) not null,
  originates_from_order boolean not null default false,
  originates_from_customer_account boolean not null default false,
  originates_from_ar boolean not null default false,
  originates_from_b2b_statement boolean not null default false,
  originates_from_wallet boolean not null default false,
  originates_from_gift_card boolean not null default false,
  originates_from_refund boolean not null default false,
  originates_from_gateway_callback boolean not null default false,
  is_manual boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_fin_voucher_source_family check (source_family in ('ORDER','CUSTOMER_ACCOUNT','AR','B2B_STATEMENT','WALLET','GIFT_CARD','ADVANCE','REFUND','GATEWAY','MANUAL','OTHER'))
);
comment on table public.sys_fin_voucher_source_type_cd is 'Catalog for voucher source/origin classification. Source answers where the voucher came from; target answers what a voucher line settles.';

-- 8. Credit application catalogs
create table if not exists public.sys_credit_application_type_cd (
  credit_application_type varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  credit_family varchar(50) not null,
  is_stored_value boolean not null default false,
  is_customer_credit boolean not null default false,
  is_credit_note boolean not null default false,
  is_loyalty boolean not null default false,
  is_manual boolean not null default false,
  requires_source_reference boolean not null default true,
  allows_partial_application boolean not null default true,
  allows_reversal boolean not null default true,
  affects_order_total boolean not null default false,
  affects_taxable_amount boolean not null default false,
  reduces_outstanding boolean not null default true,
  creates_cash_movement boolean not null default false,
  source_table text null,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_credit_application_family check (credit_family in ('GIFT_CARD','WALLET','ADVANCE','CUSTOMER_CREDIT','CREDIT_NOTE','LOYALTY','MANUAL'))
);
create table if not exists public.sys_credit_application_status_cd (
  application_status varchar(50) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  status_group varchar(50) not null,
  reduces_outstanding boolean not null default false,
  is_pending boolean not null default false,
  is_terminal boolean not null default false,
  is_success boolean not null default false,
  is_failure boolean not null default false,
  allows_reversal boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_credit_application_status_group check (status_group in ('PENDING','SUCCESS','FAILED','REVERSED'))
);

-- 9. Remaining balance and overpayment catalogs
create table if not exists public.sys_remaining_balance_policy_cd (
  policy_code varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  requires_zero_remaining boolean not null default false,
  creates_pay_on_collection_due boolean not null default false,
  creates_ar_invoice boolean not null default false,
  creates_ar_ledger boolean not null default false,
  creates_statement_entry boolean not null default false,
  requires_customer_account boolean not null default false,
  requires_b2b_customer boolean not null default false,
  requires_credit_limit_check boolean not null default false,
  requires_approval boolean not null default false,
  resulting_payment_status varchar(50) null,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create table if not exists public.sys_overpayment_resolution_cd (
  resolution_code varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  allowed_for_cash boolean not null default false,
  allowed_for_card boolean not null default false,
  allowed_for_gateway boolean not null default false,
  allowed_for_bank boolean not null default false,
  allowed_for_check boolean not null default false,
  allowed_for_mobile boolean not null default false,
  allowed_for_stored_value boolean not null default false,
  creates_change_return boolean not null default false,
  creates_payment_reduction boolean not null default false,
  creates_void_or_refund boolean not null default false,
  creates_customer_advance boolean not null default false,
  creates_customer_credit boolean not null default false,
  restores_stored_value boolean not null default false,
  creates_multi_target_allocation boolean not null default false,
  uses_allocation_policy boolean not null default false,
  requires_allocation_details boolean not null default false,
  requires_permission boolean not null default false,
  permission_code varchar(120) null,
  requires_reason boolean not null default false,
  requires_approval boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);

-- 10. Customer receipt allocation catalogs - v1.1
create table if not exists public.sys_customer_receipt_allocation_mode_cd (
  allocation_mode varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  sort_by_due_date boolean not null default false,
  sort_by_document_date boolean not null default false,
  uses_target_priority boolean not null default false,
  is_manual_only boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create table if not exists public.sys_customer_receipt_fallback_destination_cd (
  fallback_destination varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  line_role varchar(80) null,
  target_type varchar(80) null,
  creates_wallet_topup boolean not null default false,
  creates_customer_advance boolean not null default false,
  creates_customer_credit boolean not null default false,
  creates_cash_change boolean not null default false,
  blocks_posting boolean not null default false,
  requires_cash boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null
);
create table if not exists public.org_customer_receipt_allocation_policy_cf (
  id uuid not null default gen_random_uuid(),
  tenant_org_id uuid not null,
  branch_id uuid null,
  policy_code varchar(80) not null,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  is_default boolean not null default false,
  is_active boolean not null default true,
  allocation_mode varchar(80) not null default 'AUTO_OLDEST_DUE',
  include_ar_invoices boolean not null default true,
  include_b2b_statements boolean not null default true,
  include_pay_on_collection_orders boolean not null default true,
  include_open_order_balances boolean not null default true,
  priority_ar_invoices int not null default 10,
  priority_b2b_statements int not null default 20,
  priority_pay_on_collection_orders int not null default 30,
  priority_open_order_balances int not null default 40,
  allow_partial_last_target boolean not null default true,
  require_same_currency boolean not null default true,
  allow_cross_branch_allocation boolean not null default false,
  allow_cross_contract_allocation boolean not null default false,
  fallback_destination varchar(80) not null default 'CUSTOMER_ADVANCE',
  require_confirmation_before_posting boolean not null default true,
  max_targets_per_allocation int not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  rec_status smallint not null default 1,
  created_at timestamptz not null default now(),
  created_by varchar(120) null,
  updated_at timestamptz null,
  updated_by varchar(120) null,
  constraint pk_org_customer_receipt_allocation_policy_cf primary key (id, tenant_org_id),
  constraint uq_org_customer_receipt_allocation_policy_code unique (tenant_org_id, branch_id, policy_code),
  constraint fk_receipt_alloc_policy_mode foreign key (allocation_mode) references public.sys_customer_receipt_allocation_mode_cd(allocation_mode),
  constraint fk_receipt_alloc_policy_fallback foreign key (fallback_destination) references public.sys_customer_receipt_fallback_destination_cd(fallback_destination),
  constraint chk_customer_receipt_max_targets check (max_targets_per_allocation > 0)
);

-- 11. Status/tax/refund catalogs (target tables)
create table if not exists public.sys_payment_status_cd (
  payment_status varchar(50) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  status_group varchar(50) not null,
  counts_as_paid boolean not null default false,
  is_pending boolean not null default false,
  is_authorized boolean not null default false,
  is_failed boolean not null default false,
  is_terminal boolean not null default false,
  allows_capture boolean not null default false,
  allows_void boolean not null default false,
  allows_refund boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_payment_status_group check (status_group in ('PENDING','AUTHORIZED','SUCCESS','FAILED','REVERSED'))
);
create table if not exists public.sys_refund_source_type_cd (
  refund_source_type varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  refund_family varchar(50) not null,
  affects_real_payment_refunded_amount boolean not null default false,
  affects_stored_value_restored_amount boolean not null default false,
  affects_customer_credit_issued_amount boolean not null default false,
  creates_cash_out boolean not null default false,
  creates_gateway_refund boolean not null default false,
  restores_stored_value boolean not null default false,
  creates_credit_note boolean not null default false,
  requires_permission boolean not null default false,
  permission_code varchar(120) null,
  requires_reason boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_refund_source_type_family check (refund_family in ('REAL_PAYMENT','GIFT_CARD','WALLET','CUSTOMER_ADVANCE','CUSTOMER_CREDIT','CREDIT_NOTE','MANUAL'))
);
create table if not exists public.sys_tax_document_type_cd (
  tax_document_type varchar(80) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  document_family varchar(50) not null,
  is_invoice boolean not null default false,
  is_simplified boolean not null default false,
  is_standard boolean not null default false,
  is_credit_note boolean not null default false,
  is_debit_note boolean not null default false,
  affects_tax_reporting boolean not null default true,
  requires_customer_tax_id boolean not null default false,
  requires_qr boolean not null default false,
  requires_clearance boolean not null default false,
  requires_reporting boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_tax_document_type_family check (document_family in ('INVOICE','NOTE','RECEIPT','NONE'))
);
create table if not exists public.sys_tax_document_status_cd (
  tax_document_status varchar(50) primary key,
  name text not null,
  name2 text null,
  description text null,
  description2 text null,
  status_group varchar(50) not null,
  is_draft boolean not null default false,
  is_issued boolean not null default false,
  is_reported boolean not null default false,
  is_cleared boolean not null default false,
  is_failed boolean not null default false,
  is_cancelled boolean not null default false,
  is_terminal boolean not null default false,
  allows_correction_note boolean not null default false,
  display_order int null,
  is_system boolean not null default true,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint chk_sys_tax_document_status_group check (status_group in ('DRAFT','ISSUED','AUTHORITY','FAILED','CANCELLED'))
);

-- 12. Recommended indexes
create index if not exists idx_org_payment_methods_cf_tenant_branch_active on public.org_payment_methods_cf (tenant_org_id, branch_id, is_enabled, is_active);
create index if not exists idx_org_payment_methods_cf_method on public.org_payment_methods_cf (payment_method_code);
create index if not exists idx_receipt_alloc_policy_tenant_branch_active on public.org_customer_receipt_allocation_policy_cf (tenant_org_id, branch_id, is_active, is_default);
