-- ==================================================================
-- Migration: 0175_erp_lite_phase1_feature_flags.sql
-- Purpose: Seed ERP-Lite Phase 1 feature flags and plan mappings
-- Project: cleanmatex (source of truth for shared DB migrations)
-- Phase: ERP-Lite Phase 1 - Platform Enablement
-- Do NOT apply automatically. User must review and apply manually.
-- ==================================================================

BEGIN;

INSERT INTO public.hq_ff_feature_flags_mst (
  flag_key,
  flag_name,
  flag_name2,
  flag_description,
  flag_description2,
  governance_category,
  is_billable,
  is_kill_switch,
  is_sensitive,
  allowed_values,
  min_value,
  max_value,
  json_schema,
  data_type,
  default_value,
  validation_rules,
  plan_binding_type,
  enabled_plan_codes,
  allows_tenant_override,
  override_requires_approval,
  ui_group,
  ui_display_order,
  ui_icon,
  ui_color,
  is_active,
  created_by,
  created_info
) VALUES
  (
    'erp_lite_enabled',
    'ERP-Lite Enabled',
    'تفعيل ERP-Lite',
    'Master switch for the Finance & Accounting tenant module',
    'المفتاح الرئيسي لوحدة المالية والمحاسبة للمستأجر',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    true,
    false,
    'ERP-Lite',
    1,
    'Landmark',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_gl_enabled',
    'ERP-Lite GL',
    'ERP-Lite دفتر الأستاذ',
    'Enable Chart of Accounts and General Ledger shells for ERP-Lite',
    'تفعيل قوالب دليل الحسابات ودفتر الأستاذ العام لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    2,
    'BookOpen',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_reports_enabled',
    'ERP-Lite Financial Reports',
    'تقارير ERP-Lite المالية',
    'Enable ERP-Lite financial report shells',
    'تفعيل قوالب التقارير المالية لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    3,
    'BarChart3',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_ar_enabled',
    'ERP-Lite AR Aging',
    'أعمار الذمم المدينة ERP-Lite',
    'Enable ERP-Lite receivables aging shells',
    'تفعيل قوالب أعمار الذمم المدينة لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    4,
    'Clock3',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_expenses_enabled',
    'ERP-Lite Expenses',
    'مصروفات ERP-Lite',
    'Enable ERP-Lite expense and petty cash shells',
    'تفعيل قوالب المصروفات والعهدة النقدية لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    5,
    'Wallet',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_bank_recon_enabled',
    'ERP-Lite Bank Reconciliation',
    'تسوية البنك ERP-Lite',
    'Enable ERP-Lite bank reconciliation shells',
    'تفعيل قوالب تسوية البنك لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    6,
    'Landmark',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_ap_enabled',
    'ERP-Lite Accounts Payable',
    'الذمم الدائنة ERP-Lite',
    'Enable ERP-Lite accounts payable shells',
    'تفعيل قوالب الذمم الدائنة لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    7,
    'NotebookText',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_po_enabled',
    'ERP-Lite Purchase Orders',
    'أوامر الشراء ERP-Lite',
    'Enable ERP-Lite purchase order shells',
    'تفعيل قوالب أوامر الشراء لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    8,
    'ShoppingCart',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  ),
  (
    'erp_lite_branch_pl_enabled',
    'ERP-Lite Branch P&L',
    'أرباح وخسائر الفروع ERP-Lite',
    'Enable ERP-Lite branch profitability shells',
    'تفعيل قوالب أرباح وخسائر الفروع لـ ERP-Lite',
    'tenant_feature',
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    'boolean',
    to_jsonb(false),
    '[]'::jsonb,
    'plan_bound',
    '["PRO","ENTERPRISE"]'::jsonb,
    false,
    false,
    'ERP-Lite',
    9,
    'Building2',
    NULL,
    true,
    'system_seed',
    'Migration 0175 ERP-Lite Phase 1'
  )
ON CONFLICT (flag_key) DO UPDATE SET
  flag_name = EXCLUDED.flag_name,
  flag_name2 = EXCLUDED.flag_name2,
  flag_description = EXCLUDED.flag_description,
  flag_description2 = EXCLUDED.flag_description2,
  default_value = EXCLUDED.default_value,
  enabled_plan_codes = EXCLUDED.enabled_plan_codes,
  allows_tenant_override = EXCLUDED.allows_tenant_override,
  override_requires_approval = EXCLUDED.override_requires_approval,
  ui_group = EXCLUDED.ui_group,
  ui_display_order = EXCLUDED.ui_display_order,
  ui_icon = EXCLUDED.ui_icon,
  updated_at = CURRENT_TIMESTAMP,
  updated_by = 'system_seed',
  updated_info = 'Migration 0175 ERP-Lite Phase 1';

INSERT INTO public.sys_ff_pln_flag_mappings_dtl (
  plan_code,
  flag_key,
  plan_specific_value,
  is_enabled,
  notes,
  created_by,
  created_info
)
VALUES
  ('FREE_TRIAL', 'erp_lite_enabled', NULL, false, 'ERP-Lite not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_enabled', NULL, false, 'ERP-Lite not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_enabled', NULL, false, 'ERP-Lite not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_enabled', 'true'::jsonb, true, 'ERP-Lite Phase 1 enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_enabled', 'true'::jsonb, true, 'ERP-Lite Phase 1 enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_gl_enabled', NULL, false, 'GL not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_gl_enabled', NULL, false, 'GL not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_gl_enabled', NULL, false, 'GL not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_gl_enabled', 'true'::jsonb, true, 'GL enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_gl_enabled', 'true'::jsonb, true, 'GL enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_reports_enabled', NULL, false, 'Reports not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_reports_enabled', NULL, false, 'Reports not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_reports_enabled', NULL, false, 'Reports not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_reports_enabled', 'true'::jsonb, true, 'Reports enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_reports_enabled', 'true'::jsonb, true, 'Reports enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_ar_enabled', NULL, false, 'AR aging not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_ar_enabled', NULL, false, 'AR aging not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_ar_enabled', NULL, false, 'AR aging not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_ar_enabled', 'true'::jsonb, true, 'AR aging enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_ar_enabled', 'true'::jsonb, true, 'AR aging enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_expenses_enabled', NULL, false, 'Expenses not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_expenses_enabled', NULL, false, 'Expenses not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_expenses_enabled', NULL, false, 'Expenses not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_expenses_enabled', NULL, false, 'Expenses reserved for ENTERPRISE', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_expenses_enabled', 'true'::jsonb, true, 'Expenses enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_bank_recon_enabled', NULL, false, 'Bank reconciliation not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_bank_recon_enabled', NULL, false, 'Bank reconciliation not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_bank_recon_enabled', NULL, false, 'Bank reconciliation not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_bank_recon_enabled', 'true'::jsonb, true, 'Bank reconciliation enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_bank_recon_enabled', 'true'::jsonb, true, 'Bank reconciliation enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_ap_enabled', NULL, false, 'AP not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_ap_enabled', NULL, false, 'AP not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_ap_enabled', NULL, false, 'AP not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_ap_enabled', NULL, false, 'AP reserved for ENTERPRISE', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_ap_enabled', 'true'::jsonb, true, 'AP enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_po_enabled', NULL, false, 'PO not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_po_enabled', NULL, false, 'PO not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_po_enabled', NULL, false, 'PO not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_po_enabled', NULL, false, 'PO reserved for ENTERPRISE', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_po_enabled', 'true'::jsonb, true, 'PO enabled for ENTERPRISE', 'system_seed', 'Migration 0175'),

  ('FREE_TRIAL', 'erp_lite_branch_pl_enabled', NULL, false, 'Branch P&L not included in FREE_TRIAL', 'system_seed', 'Migration 0175'),
  ('STARTER', 'erp_lite_branch_pl_enabled', NULL, false, 'Branch P&L not included in STARTER', 'system_seed', 'Migration 0175'),
  ('GROWTH', 'erp_lite_branch_pl_enabled', NULL, false, 'Branch P&L not included in GROWTH', 'system_seed', 'Migration 0175'),
  ('PRO', 'erp_lite_branch_pl_enabled', 'true'::jsonb, true, 'Branch P&L enabled for PRO', 'system_seed', 'Migration 0175'),
  ('ENTERPRISE', 'erp_lite_branch_pl_enabled', 'true'::jsonb, true, 'Branch P&L enabled for ENTERPRISE', 'system_seed', 'Migration 0175')
ON CONFLICT (plan_code, flag_key) DO UPDATE SET
  plan_specific_value = EXCLUDED.plan_specific_value,
  is_enabled = EXCLUDED.is_enabled,
  notes = EXCLUDED.notes,
  updated_at = CURRENT_TIMESTAMP,
  updated_by = 'system_seed',
  updated_info = 'Migration 0175 ERP-Lite Phase 1';

COMMIT;
