-- ============================================================
-- Migration: 0594_nav_permission_only_menu.sql
-- Purpose:   Sidebar visibility follows sys_components_cd.main_permission_code.
--            NULL means every signed-in user. Feature flags still apply.
--            Role arrays are no longer a visibility gate, and one bad JSON
--            value can no longer abort the whole menu.
-- Affected:  sys_components_cd, get_navigation_with_parents_jh,
--            cmx_nav_flag_texts
-- Related:   get_navigation_with_parents_jh (navigation RPC)
-- ============================================================
--
-- ROLLBACK PLAN (forward-only): a later migration would restore the previous
-- function body and the previous main_permission_code / feature_flag / roles
-- values. Do not edit this file after it is applied.

BEGIN;

-- Turns feature_flag into text keys. A double-encoded JSON string is parsed.
-- A scalar or invalid value becomes an empty list so one row cannot abort the menu.
CREATE OR REPLACE FUNCTION public.cmx_nav_flag_texts(p_flag jsonb)
RETURNS text[]
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
DECLARE
  v_parsed jsonb;
BEGIN
  IF p_flag IS NULL OR jsonb_typeof(p_flag) = 'null' THEN
    RETURN ARRAY[]::text[];
  END IF;

  IF jsonb_typeof(p_flag) = 'array' THEN
    v_parsed := p_flag;
  ELSIF jsonb_typeof(p_flag) = 'string' AND left(btrim(p_flag #>> '{}'), 1) = '[' THEN
    BEGIN
      v_parsed := (p_flag #>> '{}')::jsonb;
    EXCEPTION
      WHEN others THEN
        RETURN ARRAY[]::text[];
    END;
  ELSE
    RETURN ARRAY[]::text[];
  END IF;

  IF jsonb_typeof(v_parsed) IS DISTINCT FROM 'array' THEN
    RETURN ARRAY[]::text[];
  END IF;

  RETURN ARRAY(SELECT jsonb_array_elements_text(v_parsed));
END;
$$;

COMMENT ON FUNCTION public.cmx_nav_flag_texts(jsonb) IS
  'Normalizes a navigation feature_flag jsonb value to text keys. Empty means no flag is required. Invalid JSON does not raise.';

-- Internal helper. The navigation RPC is SECURITY DEFINER and calls this as its owner.
REVOKE ALL ON FUNCTION public.cmx_nav_flag_texts(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cmx_nav_flag_texts(jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.cmx_nav_flag_texts(jsonb) FROM authenticated;

-- Menu rows are visible from main_permission_code plus feature flags.
-- p_user_role is kept so existing callers do not break; it is not a gate.
CREATE OR REPLACE FUNCTION public.get_navigation_with_parents_jh(
  p_user_permissions text[],
  p_user_role text DEFAULT NULL,
  p_feature_flags jsonb DEFAULT '[]'::jsonb
)
RETURNS TABLE(
  comp_id uuid,
  parent_comp_id uuid,
  comp_code text,
  parent_comp_code text,
  label text,
  label2 text,
  comp_path text,
  comp_icon character varying,
  badge text,
  display_order integer,
  comp_level integer,
  is_leaf boolean,
  roles jsonb,
  permissions jsonb,
  require_all_permissions boolean,
  feature_flag jsonb,
  main_permission_code text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_flags text[] := ARRAY[]::text[];
BEGIN
  -- p_user_role stays in the signature for existing callers. Visibility does not use it.
  IF jsonb_typeof(COALESCE(p_feature_flags, '[]'::jsonb)) = 'array' THEN
    v_flags := ARRAY(SELECT jsonb_array_elements_text(COALESCE(p_feature_flags, '[]'::jsonb)));
  END IF;

  RETURN QUERY
  WITH RECURSIVE visible_items AS (
    SELECT
      c.comp_id,
      c.parent_comp_id,
      c.comp_code,
      c.parent_comp_code,
      c.label,
      c.label2,
      c.comp_path,
      c.comp_icon,
      c.badge,
      c.display_order,
      c.comp_level,
      c.is_leaf,
      c.roles,
      c.permissions,
      c.require_all_permissions,
      c.feature_flag,
      c.main_permission_code
    FROM sys_components_cd c
    WHERE c.is_active = true
      AND c.is_navigable = true
      AND (
        -- NULL or blank: every signed-in user. Any other value must be held.
        c.main_permission_code IS NULL
        OR btrim(c.main_permission_code) = ''
        OR c.main_permission_code = ANY(COALESCE(p_user_permissions, ARRAY[]::text[]))
      )
      AND (
        cardinality(public.cmx_nav_flag_texts(c.feature_flag)) = 0
        OR public.cmx_nav_flag_texts(c.feature_flag) && v_flags
      )

    UNION

    -- Parents of a visible row stay in the tree even when their own permission does not match.
    SELECT
      p.comp_id,
      p.parent_comp_id,
      p.comp_code,
      p.parent_comp_code,
      p.label,
      p.label2,
      p.comp_path,
      p.comp_icon,
      p.badge,
      p.display_order,
      p.comp_level,
      p.is_leaf,
      p.roles,
      p.permissions,
      p.require_all_permissions,
      p.feature_flag,
      p.main_permission_code
    FROM sys_components_cd p
    INNER JOIN visible_items v ON p.comp_id = v.parent_comp_id
    WHERE p.is_active = true
      AND p.is_navigable = true
  )
  SELECT DISTINCT
    vi.comp_id,
    vi.parent_comp_id,
    vi.comp_code,
    vi.parent_comp_code,
    vi.label,
    vi.label2,
    vi.comp_path,
    vi.comp_icon,
    vi.badge,
    vi.display_order,
    vi.comp_level,
    vi.is_leaf,
    vi.roles,
    vi.permissions,
    vi.require_all_permissions,
    vi.feature_flag,
    vi.main_permission_code
  FROM visible_items vi
  ORDER BY vi.comp_level NULLS FIRST, vi.display_order NULLS LAST;
END;
$$;

COMMENT ON FUNCTION public.get_navigation_with_parents_jh(text[], text, jsonb) IS
  'Returns navigable menu rows for a signed-in user. main_permission_code NULL means every signed-in user. A set code must be in p_user_permissions. Feature flags still apply. p_user_role is ignored. Parents of visible rows are included.';

COMMENT ON COLUMN public.sys_components_cd.main_permission_code IS
  'Permission code required to show this menu row. NULL means every signed-in user. Visibility does not use the roles column.';

COMMENT ON COLUMN public.sys_components_cd.roles IS
  'Legacy audience list. The menu RPC does not use this column for visibility.';

-- These codes must already exist. Refuse to publish a menu gate that no role can hold.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM (VALUES
      ('admin:manage'),
      ('orders:read'),
      ('settings:read'),
      ('settings:subscription')
    ) AS required(code)
    WHERE NOT EXISTS (
      SELECT 1
      FROM public.sys_auth_permissions p
      WHERE p.code = required.code
        AND p.is_active = true
    )
  ) THEN
    RAISE EXCEPTION 'nav permission-only menu: a required permission code is missing or inactive';
  END IF;
END;
$$;

-- Repair double-encoded role lists so later readers do not call jsonb array functions on a string.
UPDATE public.sys_components_cd
SET roles = (roles #>> '{}')::jsonb
WHERE jsonb_typeof(roles) = 'string'
  AND left(btrim(roles #>> '{}'), 1) = '['
  AND jsonb_typeof((roles #>> '{}')::jsonb) = 'array';

-- orders_packing stored role codes with extra quotes, so no real role code could match.
UPDATE public.sys_components_cd
SET roles = (
  SELECT COALESCE(jsonb_agg(replace(elem, '''', '')), '[]'::jsonb)
  FROM jsonb_array_elements_text(roles) AS elem
)
WHERE comp_code = 'orders_packing'
  AND jsonb_typeof(roles) = 'array';

-- Repair double-encoded feature flags. reports was a JSON string and crashed the old menu RPC.
UPDATE public.sys_components_cd
SET feature_flag = (feature_flag #>> '{}')::jsonb
WHERE jsonb_typeof(feature_flag) = 'string'
  AND left(btrim(feature_flag #>> '{}'), 1) = '['
  AND jsonb_typeof((feature_flag #>> '{}')::jsonb) = 'array';

-- These nulls were missing data, not an "everyone" choice.
UPDATE public.sys_components_cd
SET main_permission_code = 'admin:manage'
WHERE comp_code = 'jhtestui';

UPDATE public.sys_components_cd
SET main_permission_code = 'orders:read'
WHERE comp_code = 'orders_issues';

UPDATE public.sys_components_cd
SET main_permission_code = 'settings:read'
WHERE comp_code = 'config_settings';

UPDATE public.sys_components_cd
SET main_permission_code = 'settings:subscription'
WHERE comp_code IN ('tenant_admin', 'tenant_admin_subscription');

-- Reports hub was tagged orders:read, so every order reader would see it.
-- The page gate is the advanced_analytics flag, not a permission.
UPDATE public.sys_components_cd
SET
  main_permission_code = NULL,
  feature_flag = '["advanced_analytics"]'::jsonb
WHERE comp_code = 'reports';

-- These five stored a role list in the permission column, so they never matched a permission.
UPDATE public.sys_components_cd
SET main_permission_code = NULL
WHERE comp_code IN (
  'reports_orders',
  'reports_payments',
  'reports_invoices',
  'reports_revenue',
  'reports_customers'
);

-- These pages require the analytics flag in the access contract. The menu must too.
UPDATE public.sys_components_cd
SET feature_flag = '["advanced_analytics"]'::jsonb
WHERE comp_code IN ('reports_financial', 'reports_reconciliation');

COMMIT;
